### ISSUE TITLE
View transition support

### ISSUE THREAD

**Issue by ansarizafar** [howesteve/elegua#4]
Thanks for amazing project. I also hate file based routing and I really like elegua router. Is there any plan to add support for view transitions?

**Comment by howesteve** [comment]
Glad you like it. What do you mean by "view transitions"? Could you be more specific? Do you mean the new, experimental  [View Transitions API ](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API)?

**Comment by ansarizafar** [comment]
Yes I mean the new experimental view transitions API.  Sveltekit has an open PR and Astro also has a support for view transitions.

**Comment by howesteve** [comment]
Except if I'm missing something, that API was made to fix the animation's problem in non-SPA applications where app state is lost between navigation. In svelte/SPAs, including Elegua, you can just use plain [svelte animations](https://svelte.dev/docs/svelte-animate) and it should work out of the box. So I don't see the need in implementing support for non-SPA animations in a SPA router. 
Let me know if that makes sense.

**Comment by howesteve** [comment]
Closing as per lack of reply. Feel free to reopen.
