### ISSUE TITLE
Component loading after a resolve call, before the params store is set

### ISSUE THREAD

**Issue by ariroffe** [howesteve/elegua#8]
Hi! Firstly, thanks for all the work put into writing this package! I think it is really neat.

I don't really know if this is a bug or if it is intended behaviour, but I was following the examples and run into the following issue (very simplified, for clarity):

### App.svelte

    <script>
      import {path, resolve, params} from 'elegua';
      import Foo from './Foo.svelte';
  
      async function getUser() {
        console.log("Here I get the currently logged in user from the backend and save it in a store")
        return null
      }
    </script>
    
    <main>
      {#await getUser()}
        Loading...
      {:then _}
        {#if resolve($path, 'foo/:slug')}
          <Foo slug={$params['slug']} />
        {:else}
          404
        {/if}
      {/await}
    </main>

### Foo.svelte

    <script>
      export let slug;
      
      async function queryBackend() {
        console.log(`Here we query the backend with slug ${slug}`)
      }
    </script>
    
    {#await queryBackend()}
      Loading...
    {:then _}
      <h1>Foo component</h1>
    {/await}

The issue I have is that the backend call from the Foo component is executed before the `$params` store is set. I.e., the `queryBackend` function is printing "Here we query the backend with slug undefined".

This can be fixed in two ways, firstly by changing `slug` in the Foo component for `$params['slug']`, or by doing an `await tick()` at the beginning of `queryBackend`.

So the question is: Is this intended behaviour? (in which case, it would be nice to document that it can happen). If not, is there any way to guarantee that the `params` store is set before `resolve` returns?

**Comment by howesteve** [comment]
That's not related to elegua. It's regular svelte/js behavior because you're calling `{#await queryBackend()}` right away when you import `Foo.svelte` from `App.svelte`. Elegua has no influence on the modules loading order. 
It seems you think `Foo` will be loaded and executed just when it's `App` block is rendered? But no, it's loaded right at the ` import Foo from './Foo.svelte'` line.
I suggest you call the `queryBackend()` inside an onMount() handler and work from there.

**Comment by ariroffe** [comment]
Thanks for your reply. I suspected that this is not an elegua problem, but rather one concerning the order in which Svelte executes code. But, just to correctly understand what is going on, let me point out the following. 

Changing Foo.svelte for this:

    <script>
      import {onMount} from 'svelte';
    
      export let slug;
      
      onMount(queryBackend);
      
      async function queryBackend() {
        console.log(`Here we query the backend with slug ${slug}`)
      }
    </script>

    <h1>Foo component</h1>
 
does not solve the issue. The console still logs "Here we query the backend with slug undefined".

Moreover, if I define a third component Bar.svelte with the following contents:

    <script>
      console.log('Bar component init')
      async function queryBackend() {
        console.log('Query from Bar component')
      }
    </script>

    {#await queryBackend()}
      Loading...
    {:then _}
      <h1>Bar component</h1>
    {/await}

And just add an `import Bar from './Bar.svelte'` line in App.svelte, then nothing is logged from that component (it is **not** executed at the import line).

My hypothesis (I am kind of new to Svelte, so take it with a grain of salt) is that Svelte does not see the dependency of `queryBackend` on `$params`, so -for some reason- it is running that async code before it updates the store. 

That is why my suggestion was to document that `$params` may not yet be updated when another component is initialized.

**Comment by howesteve** [comment]
Your updated code will surely print the message because you're calling the main function directly. I guess you need to be more used to svelte. 

As per docs, there is this note stating clearly that `$params` will be defined only after a `resolve()` call:
> `Just as with [$match](https://github.com/howesteve/elegua#match), [$params](https://github.com/howesteve/elegua#params) is only updated after a [resolve()](https://github.com/howesteve/elegua#resolve) call. Specifically, [$path](https://github.com/howesteve/elegua#path)-based routing will not update these stores.

The problem here is, you're calling `queryBackend()` right away, **before** the browser triggers any history events, so resolve() is not called yet and  `params` is not defined.

Perhaps what you want is something like this?

```svelte
<script lang="ts">
  import { params } from 'elegua';
  async function queryBackend(slug: string) {
    // simulating slow server query
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
      slug: slug,
      contents: "xxxx"
    };
  }
</script>

{#if $params['slug']}
  {#await queryBackend($params['slug'])}
    <h1>Loading...</h1>
  {:then post}
    <h1>Post: {post.slug}</h1>
    <p>Contents: {post.contents}</p>
  {/await}
{/if}
```

**Comment by ariroffe** [comment]
Ok, there's clearly something about the way Svelte works that I'm not understanding, so if you feel that this isn't productive feel free to close the issue. 

To clarify, in my second post I was only proposing to modify Foo.svelte while keeping App.svelte identical. Here is a fuller version of the code that is giving me doubts. I will log everything that happens to see what is being called in what order:

### App.svelte

```svelte
<script>
  import {path, resolve, params} from 'elegua';
  import Foo from './Foo.svelte';
 
  async function getUser() {
    console.log("getUser function called")
  }
  
  function callResolve() {
    console.log("Calling resolve")
    let result = resolve($path, 'foo/:slug')
    console.log(`Resolve has returned, params are: ${JSON.stringify($params)}`)
    return result
  }
</script>

<main>
  {#await getUser()}
    Loading...
  {:then _}
    {#if callResolve()}
      {console.log(`We are inside the #if block with params ${JSON.stringify($params)}`)}
      <Foo slug={$params['slug']} />
    {:else}
      404
    {/if}
  {/await}
</main>
```

### Foo.svelte

```svelte
<script>
  import {onMount} from 'svelte';
  
  export let slug;
  
  async function queryBackend() {
    console.log(`Calling queryBackend from Foo with slug ${slug}`)
  }
  
  console.log("Foo component initialized")

  onMount(() => console.log("Foo component mounted"))
</script>

{#await queryBackend()}
  Loading...
{:then _}
  <h1>Foo component</h1>
{/await}
```

If I navigate to `main-url/foo/hello/` I get the following log:

```
getUser function called
Calling resolve
Resolve has returned, params are: {"slug":"hello"}
We are inside the #if block with params {}
Foo component initialized
Calling queryBackend from Foo with slug undefined
We are inside the #if block with params {"slug":"hello"}
Foo component mounted
```

What seems to be happening is:
1. Svelte initializes App.svelte, it calls the function in the `#await` block, and moves on to the `:then` clause. 
2. There, it finds an `#if` block and evaluates the condition. The condition calls `resolve`, which sets the `params` store (the result is logged in line 3). 
3. Svelte then moves over to the body of the `#if` block. Here `params` seems to not be set (!!!)
4. Therefore, it initializes the Foo component with `slug=undefined`
5. Code in the Foo `<script>` tag runs
6. After all this happens, the body of the `#if` block in App.svelte gets notified that `params` has been set.
7. Finally, the Foo component is considered to be mounted

Again, I know that this is not an elegua problem, so you can feel free to close the issue. But if you can help me understand what is going on, I will be very thankful. Especially in step 3, why does the body of the `#if` block not immediately see the value of `params`?

**Comment by howesteve** [comment]
Again, it's because you're calling `queryBackend()` right away, before `$params` is defined, i.e. before `resolve()` was called. You think `resolve()` was already called at by when `queryBackend()` was called, but it's not. _The code loading order is not the same as the routing order_. It's a racing condition. Try wrapping the await block as previously suggested, like this, and keep the rest of your code.

```svelte
{#if $params['slug']}
  {#await queryBackend()}
    Loading...
  {:then _}
    <h1>Foo component</h1>
  {/await}
{/if}
```
