### ISSUE TITLE
Resolve always matches beyond the specified string when using named params

### ISSUE THREAD

**Issue by ariroffe** [howesteve/elegua#9]
For example, in the demo page:

```svelte
{#if resolve($path, '/blog/:post')}
  <Post id={$params['post']}
```

the resolve call will return `true` for urls such as `https://elegua.netlify.app/blog/fake-post-0/abc` (see [here](https://elegua.netlify.app/blog/fake-post-0/abc) or [here](https://elegua.netlify.app/users/755/abc))

If I'm not mistaken, can be fixed by adding a `$` at the end of `namedPath`:

```typescript
export function namedPath(route: string): RegExp {
  // checking for named component paths
  return RegExp(
    route.split('/').map((x) =>
        x.startsWith(':') ? `(?<${regExpEscape(x.slice(1, x.length))}>[a-zA-Z0-9][a-zA-Z0-9\_\-]*)` : regExpEscape(x)
      ).join(`\\/`) + '$'
  );
}
```

**Comment by howesteve** [comment]
Good catch, I've fixed it on the latest version and released it.

**Comment by ariroffe** [comment]
Thanks for the fix! 

Sorry to be a pain, but I was just thinking, won't this still be a problem for regexp-based routes? Since they will not go into the `namedPath` function and therefore will not get the new `$` at the end. For example, in the demo website, the route `/users\/([0-9]+)/` still matches this: [https://elegua.netlify.app/users/998/abc/def/](https://elegua.netlify.app/users/998/abc/def/)

**Comment by howesteve** [comment]
regexp routes are not affected by `namedPath()`, so that will not change it's current behavior. The url:

https://elegua.netlify.app/users/998/abc/def/

... matches because it's defined as this in the demo:
```ts
{:else if resolve($path, /users\/(?<user_id>[0-9]+)/)}
```
If you want it not to match the extra path, just add the '$' to the regexp:
```ts
{:else if resolve($path, /users\/(?<user_id>[0-9]+)$/)}
```
... and I think it will function as you desire.
